fix: shell command

diff --git a/apps/x86_64-linux/install b/apps/x86_64-linux/install
--- a/apps/x86_64-linux/install
+++ b/apps/x86_64-linux/install
@@ -24,19 +24,22 @@ cleanup() {
 }
 
 # Function to check if a command is available, and use Nix if not
-create_shell() {
-  echo -e "${YELLOW}Create a shell that provides unzip, curl and wget.${NC}"
-  nix shell --extra-experimental-features 'nix-command flakes' nixpkgs#unzip nixpkgs#curl nixpkgs#wget 
+check_and_run() {
+  local cmd="$1"
+  shift
+  if ! command -v "$cmd" >/dev/null 2>&1; then
+    echo -e "${YELLOW}${cmd} not found. Using Nix to provide it...${NC}"
+    nix shell --extra-experimental-features 'nix-command flakes' "nixpkgs#${cmd}" -c "${cmd}" "$@"
+  else
+    "${cmd}" "$@"
+  fi
 }
 
-exit_shell() {
-  exit
-}
 
 download_config() {
   echo "${YELLOW}Downloading Nix Configuration...${NC}"
-  curl -LJ0 https://github.com/$REPO/archive/$BRANCH.zip -o nixos-config-$BRANCH.zip
-  unzip nixos-config-$BRANCH.zip
+  check_and_run curl -LJ0 https://github.com/$REPO/archive/$BRANCH.zip -o nixos-config-$BRANCH.zip
+  check_and_run unzip nixos-config-$BRANCH.zip
   mv nixos-config-$BRANCH nixos-config
   cd nixos-config
 }
@@ -116,7 +119,7 @@ install_nvidia_drivers() {
     URL="https://developer.download.nvidia.com/compute/cuda/repos/${OS_ID}${OS_VERSION_ID}/${ARCH_PATH}/cuda-keyring_1.1-1_all.deb"
     echo -e "${BLUE}Adding NVIDIA package repositories...${NC}"
     # Add the NVIDIA CUDA keyring and repo
-    wget $URL
+    check_and_run wget $URL
     sudo dpkg -i cuda-keyring_1.1-1_all.deb
     sudo apt-get update
     sudo apt-get -y install cuda
@@ -140,7 +143,6 @@ install_nvidia_drivers() {
 # Main script execution
 cleanup
 check_installer
-create_shell
 download_config
 run_apply
 check_nvidia
@@ -160,5 +162,4 @@ case $? in
     ;;
 esac
 cleanup
-exit_shell
 prompt_reboot
